include examples
Premian-Labs/v3-abi pull request #8
Opened 2023-12-12 12:35 UTC by Guceri

- include link to smart contract docs
- create examples of how to use package

2023-12-12 13:01 UTC, Lumyo commented on README.md
> +const pool = new Contract(poolAddress, poolAbi, provider)
```suggestion
const pool = new Contract(poolAddress, IPool__abi, signer)
```

2023-12-12 16:27 UTC, 0xCourtney requested changes

2023-12-12 16:27 UTC, 0xCourtney commented on README.md
> +// Importing of ABIs (typechain)
```suggestion
// Importing of Typechain contract bindings

2023-12-12 16:27 UTC, 0xCourtney commented on README.md
> +import {IPoolFactory__abi} from "@premia/v3-abi/abi";
Ignore if this was done on purpose for some reason but normally I'd have a single import for each import path.

```suggestion
import {IPool__abi, IPoolFactory__abi} from "@premia/v3-abi/abi"
```

2023-12-13 18:56 UTC, 0xCourtney approved these changes

2023-12-13 18:57 UTC, merged